#!/bin/sh
# Setup a machine for VSCode
set -x

vscode_dir=~/Library/Application\ Support/Code
ln -s "$PWD/User" "$vscode_dir/User"

code --install-extension bierner.markdown-emoji
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension christopherstyles.html-entities
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension ionutvmi.path-autocomplete
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension kamikillerto.vscode-colorize
code --install-extension mikestead.dotenv
code --install-extension raillyhugo.one-hunter
code --install-extension redhat.vscode-yaml
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension smulyono.reveal
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension tedisagolli.hex-to-tailwind
code --install-extension unifiedjs.vscode-mdx
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
code --install-extension adpyke.codesnap
code --install-extension Atishay-Jain.All-Autocomplete
code --install-extension formulahendry.auto-rename-tag
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension johnsoncodehk.vscode-code-spotlight
code --install-extension MarkosTh09.color-picker
code --install-extension mrmlnc.vscode-duplicate
code --install-extension nhoizey.gremlins
code --install-extension Prisma.prisma
code --install-extension tamasfe.even-better-toml
code --install-extension usernamehw.errorlens
code --install-extension wix.vscode-import-cost
code --install-extension ziyasal.vscode-open-in-github
code --install-extension znck.grammarly
